name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p profile-3d-contrib

      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: arthurharysson
          THEME: night-green
          OUTPUT: profile-3d-contrib/profile-night-green.svg

      - name: List files after action
        run: ls -la profile-3d-contrib || echo "pasta não existe"

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/profile-night-green.svg
          git commit -m "Update 3D contribution graph" || echo "No changes"
          git push
